### ISSUE TITLE
156 more solutions?

### ISSUE THREAD

**Issue by jan100099** [renatoathaydes/prechelt-phone-number-encoding#10]
Hi, I tried to code my solution to this study using c++17  (using 4h) following the instructions in flownet.com link.

Running with your dictionary.txt and input.txt my program produces all the solutions in your output, but in addition outputs 156 more solutions.

I tried to manually check two of these extra 'solutions', which seem to be correct:
```
/78698/37395746288: bo"ig 8 Sud gab Tirol
                    78 69 8 373 957 46288
657205-851: im 7 wem Pan
            65 7 205 851
```
???

**Comment by renatoathaydes** [comment]
You probably ran into one of the ambiguities in the requirements.

Notice taht the solutions you printed are incorrect if you interpret the requirements as saying that if a word can be used on a position, you must not print other solutions that start with a digit on that position.

Let me know if you need more clarifications. This is a known issue and I myself thought the same thing when I did it first time.

**Comment by jan100099** [comment]
Thank you for your swift reply.

Yes your are right, when I added code to suppress generation of solution using single digit in the situation you stated, my solution now produces the correct output. I believe it even runs 20% faster now :-)

I have not yet looked at the solutions in your repository, so I look forward to learn how the experts solved this!

**Comment by renatoathaydes** [comment]
Cool, it seems a lot of people did the same thing, including me.

There are many branches in this repo, so make sure to check a few of them as in master the solutions are not optimized. feel free to submit your code as a pull request, and including it in the benchmark.
