### ISSUE TITLE
Benchmark doesn't run on non-Mac OS

### ISSUE THREAD

**Issue by renatoathaydes** [renatoathaydes/prechelt-phone-number-encoding#6]
Because of the memory collection in benchmark_runner using a Mac-specific API, the benchmarks cannot be run on non-Mac OS.

**Comment by renatoathaydes** [comment]
If anyone has this problem, apply this commit on your local branch and it will stop collecting memory, so will work on any OS:

https://github.com/renatoathaydes/prechelt-phone-number-encoding/commit/2b7261c0dd51f16b13986e5568aa0d19e79ea0a4

I hope someone can help actually fix the benchmark_runner so it can also get memory on other operating systems, but for now this should do!

**Comment by iffy** [comment]
I'm guessing that's this error?

```
Compiling Rust sources
    Finished release [optimized] target(s) in 0.15s
   Compiling benchmark_runner v0.1.0 (/code/src/rust/benchmark_runner)
error[E0432]: unresolved import `libproc::libproc::pid_rusage`
 --> src/main.rs:7:23
  |
7 | use libproc::libproc::pid_rusage::{pidrusage, RUsageInfoV4};
  |                       ^^^^^^^^^^ could not find `pid_rusage` in `libproc`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `benchmark_runner` due to previous error
```

**Comment by renatoathaydes** [comment]
Yes, `libproc` doesn't support collecting memory in any OS other than MacOS. I [contacted the author](https://github.com/andrewdavidmackenzie/libproc-rs/issues/61) of the library and he apparently added support on Linux, but I still couldn't get it working , I think the change was not released yet?!

Using some other library might be the best way to fix this.

**Comment by renatoathaydes** [comment]
I [upgraded the library](https://github.com/renatoathaydes/prechelt-phone-number-encoding/commit/9b1d7f026943841638a2729922cf000b1b3ce655) and it now works on Linux (not sure if it works on Windows).
